import { LoadingSpinner } from "@/components/LoadingSpinner";
import { Navbar } from "@/components/Navbar";
import { MobileListing } from "@/mobile/listing";
import { api } from "@/utils/api";
import { MIN_WIDTH } from "@/utils/constants";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function Listing() {
  const [windowWidth, setWindowWidth] = useState(0);
  const router = useRouter();

  useEffect(() => {
    const width = window.innerWidth;
    setWindowWidth(width);
  }, [windowWidth]);

  const { city } = router.query;
  const { data, isLoading } = api.hotel.getAllByCity.useQuery({
    city: city as string,
  });

  if (isLoading) return <LoadingSpinner />;

  return (
    <>
      <Head>
        <title>Hourly Hotels in {city}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {windowWidth < MIN_WIDTH ? (
        <MobileListing data={data} />
      ) : (
        <>
          <Navbar />
          <main>
            <h1>hi</h1>
          </main>
        </>
      )}
    </>
  );
}
