import { Navbar } from "@/components/Navbar";
import { TbPhoneCall, TbCurrentLocation } from "react-icons/tb";
import { HiOutlineMailOpen } from "react-icons/hi";
import Head from "next/head";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact and Support - Flexistay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen">
        <Navbar mobile={true} />
        <div className="mx-6 mt-6 mb-24">
          <h1 className="text-center text-4xl font-bold text-brand-primary">
            Contact Us
          </h1>
          <div
            id="cards"
            className="mt-8 flex flex-col items-center justify-center md:flex-row"
          >
            <div
              id="innov-card"
              className="mb-8 flex flex-col items-center justify-center md:mb-0 md:min-w-[16rem]"
            >
              <a href="mailto:support@flexistay.co.in">
                <div className="flex h-28 w-28 items-center justify-center rounded-2xl border-2 border-brand-primary shadow-2xl">
                  <HiOutlineMailOpen className="text-8xl text-brand-primary" />
                </div>
              </a>
              <a href="mailto:support@flexistay.co.in">
                <h3 className="pt-5 text-center text-xl font-semibold text-brand-primary">
                  support@flexistay.co.in
                </h3>
              </a>
            </div>
            <div
              id="customer-card"
              className="mb-8 flex flex-col  items-center justify-around md:mb-0 md:min-w-[16rem]"
            >
              <a href="tel:9284816254">
                <div className="flex h-28 w-28 items-center justify-center rounded-2xl border-2 border-brand-primary shadow-2xl">
                  <TbPhoneCall className="text-8xl text-brand-primary" />
                </div>
              </a>
              <a href="tel:9284816254">
                <h3 className="pt-5 text-center text-xl font-semibold text-brand-primary">
                  +91-9561236254
                </h3>
              </a>
            </div>
            <div
              id="customer-card"
              className="flex flex-col items-center justify-center md:min-w-[16rem]"
            >
              <div className="flex h-28 w-28 items-center justify-center rounded-2xl border-2 border-brand-primary shadow-2xl">
                <TbCurrentLocation className="text-8xl text-brand-primary" />
              </div>
              <h3 className="pt-5 text-center text-xl font-semibold text-brand-primary">
                J 01, AWHO Vijay Vihar, <br /> Wagholi, Pune-412207
              </h3>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
