import { Navbar } from "@/components/Navbar";
import { MobileListing } from "@/mobile/listing";
import { MIN_WIDTH } from "@/utils/constants";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Listing() {
  const [windowWidth, setWindowWidth] = useState(0);

  useEffect(() => {
    const width = window.innerWidth;
    setWindowWidth(width);
  }, [windowWidth]);
  return (
    <>
      <Head>
        <title>Hourly Hotels in Bangalore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {windowWidth < MIN_WIDTH ? (
        <MobileListing />
      ) : (
        <>
          <Navbar />
          <main>
            <h1>hi</h1>
          </main>
        </>
      )}
    </>
  );
}
